# Generated by Django 4.2.10 on 2024-02-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ysername', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
