# Generated by Django 4.2.10 on 2024-02-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_master',
            old_name='ysername',
            new_name='username',
        ),
    ]
