# Generated by Django 4.2.10 on 2024-02-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_ysername_user_master_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=40)),
            ],
        ),
    ]
